import axios from 'axios';
import Head from 'next/head';
import { GetServerSidePropsContext } from 'next';
import { ReactElement, useEffect } from 'react';
import { NextPageWithLayout } from '@/pages/_app';
import { IVideo } from '@/types/video';
import { Layout } from '@/components/layout';
import { BASE_URL } from '@/utils/constants';
import useVideoStore from '@/store/video-store';
import { HomeVideoList } from '@/modules/video-list';

interface IVideoResponse {
  videos: IVideo[];
  total: number;
}

const Home: NextPageWithLayout<IVideoResponse> = ({ videos, total }) => {
  const { setVideos, setTotalVideos } = useVideoStore();

  useEffect(() => {
    setVideos(videos);
    setTotalVideos(total);
  }, [videos, total]);

  return (
    <>
      <Head>
        <title>Tak-Tak</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <HomeVideoList />
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export async function getServerSideProps({ query }: GetServerSidePropsContext) {
  const { topic } = query;
  let response;

  if (topic) {
    console.log('topic', topic);
    const { data } = await axios.get<IVideoResponse>(`${BASE_URL}/api/discover/${topic}`);
    response = data;
  } else {
    const { data } = await axios.get<IVideoResponse>(`${BASE_URL}/api/post`);
    response = data;
  }

  return {
    props: {
      ...response,
    },
  };
}

export default Home;
